import sys
import os
import urllib.request

try:
    import yaml
except ImportError:
    os.system("pip install -q pyyaml")
    import yaml

output_path = sys.argv[1]
repos = sys.argv[2:]
org = os.environ["ORG"]
token = os.environ["GH_TOKEN"]

all_beers = []

for repo in repos:
    if not repo:
        continue
    url = "https://api.github.com/repos/{}/{}/contents/beer.yml".format(org, repo)
    req = urllib.request.Request(
        url,
        headers={
            "Authorization": "Bearer " + token,
            "Accept": "application/vnd.github.raw+json",
        },
    )
    try:
        with urllib.request.urlopen(req) as resp:
            raw = resp.read().decode()
    except Exception as e:
        print("  No beer.yml in {} ({}), skipping.".format(repo, e))
        continue

    print("  Adding beer(s) from {}".format(repo))
    data = yaml.safe_load(raw)

    # Normalize: a single-beer mapping becomes a one-element list
    if isinstance(data, dict):
        data = [data]

    if isinstance(data, list):
        all_beers.extend(data)
    else:
        print("  Unexpected beer.yml format in {}, skipping.".format(repo))

header = "# Auto-generated by sync-beers workflow. Do not edit manually.\n"
with open(output_path, "w") as f:
    f.write(header)
    if all_beers:
        yaml.dump(all_beers, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    else:
        f.write("[]\n")

print("\nGenerated {}:".format(output_path))
with open(output_path) as f:
    print(f.read())
